on: [push]

jobs:
  build_with_docker:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build/Compile
      id: build
      run: make